<?php

namespace Database\Seeders;

use Illuminate\Foundation\Auth\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class EmployeeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $employeeDataList = [
            [
                'alternatif' => 'A1',
                'username' => 'Cornelius2018',
                'email' => 'cornelius.rain@example.com',
                'password' => bcrypt('Cornelius2018'),
                'fullname' => 'Cornelius Rain',
                'gender' => 'Pria',
                'departement' => 'Account Receivable',
                'workYears' => '2018',
                'employeementStatus' => 'Tetap',
                'role' => 'employee',
                'status' => 'Tidak Aktif',
            ],
            [
                'alternatif' => 'A2',
                'username' => 'Irfan2018',
                'email' => 'irfan.setiadi@example.com',
                'password' => bcrypt('Irfan2018'),
                'fullname' => 'Irfan Setiadi',
                'gender' => 'Pria',
                'departement' => 'Account Receivable',
                'workYears' => '2018',
                'employeementStatus' => 'Tetap',
                'role' => 'employee',
                'status' => 'Tidak Aktif',
            ],
            [
                'alternatif' => 'A3',
                'username' => 'Dedi2019',
                'email' => 'dedi.abdurahman@example.com',
                'password' => bcrypt('Dedi2019'),
                'fullname' => 'Dedi Abdurahman',
                'gender' => 'Pria',
                'departement' => 'Account Receivable',
                'workYears' => '2019',
                'employeementStatus' => 'Tetap',
                'role' => 'employee',
                'status' => 'Tidak Aktif',
            ],
            [
                'alternatif' => 'A4',
                'username' => 'Anggi2023',
                'email' => 'anggi.dewi@example.com',
                'password' => bcrypt('Anggi2023'),
                'fullname' => 'Anggi Dewi Melati',
                'gender' => 'Wanita',
                'departement' => 'Account Receivable',
                'workYears' => '2023',
                'employeementStatus' => 'Kontrak',
                'role' => 'employee',
                'status' => 'Tidak Aktif',
            ],
            [
                'alternatif' => 'A5',
                'username' => 'Bunga2023',
                'email' => 'bunga.ayu@example.com',
                'password' => bcrypt('Bunga2023'),
                'fullname' => 'Bunga Ayu Lestari',
                'gender' => 'Wanita',
                'departement' => 'Account Receivable',
                'workYears' => '2023',
                'employeementStatus' => 'Kontrak',
                'role' => 'employee',
                'status' => 'Tidak Aktif',
            ],
            [
                'alternatif' => 'A6',
                'username' => 'Herru2019',
                'email' => 'herru.handiayana@example.com',
                'password' => bcrypt('Herru2019'),
                'fullname' => 'Herru Handiyana',
                'gender' => 'Pria',
                'departement' => 'Security',
                'workYears' => '2019',
                'employeementStatus' => 'Tetap',
                'role' => 'employee',
                'status' => 'Tidak Aktif',
            ],
            [
                'alternatif' => 'A7',
                'username' => 'Fajar2020',
                'email' => 'fajar.nugraha@example.com',
                'password' => bcrypt('Fajar2020'),
                'fullname' => 'Fajar Nugraha Ramdhani',
                'gender' => 'Pria',
                'departement' => 'Security',
                'workYears' => '2020',
                'employeementStatus' => 'Tetap',
                'role' => 'employee',
                'status' => 'Tidak Aktif',
            ],
            [
                'alternatif' => 'A8',
                'username' => 'Joko2022',
                'email' => 'joko.susilo@example.com',
                'password' => bcrypt('Joko2022'),
                'fullname' => 'Joko Susilo Hartono',
                'gender' => 'Pria',
                'departement' => 'Security',
                'workYears' => '2022',
                'employeementStatus' => 'Kontrak',
                'role' => 'employee',
                'status' => 'Tidak Aktif',
            ],
            [
                'alternatif' => 'A9',
                'username' => 'Eko2023',
                'email' => 'eko.putra@example.com',
                'password' => bcrypt('Eko2023'),
                'fullname' => 'Eko Putra Ramdani',
                'gender' => 'Pria',
                'departement' => 'Security',
                'workYears' => '2023',
                'employeementStatus' => 'Kontrak',
                'role' => 'employee',
                'status' => 'Tidak Aktif',
            ],
            [
                'alternatif' => 'A10',
                'username' => 'Gunawan2023',
                'email' => 'gunawan@example.com',
                'password' => bcrypt('Gunawan2023'),
                'fullname' => 'Gunawan',
                'gender' => 'Pria',
                'departement' => 'Security',
                'workYears' => '2023',
                'employeementStatus' => 'Kontrak',
                'role' => 'employee',
                'status' => 'Tidak Aktif',
            ],
            [
                'alternatif' => 'A11',
                'username' => 'Eko2024',
                'email' => 'eko.wijaya@example.com',
                'password' => bcrypt('Eko2024'),
                'fullname' => 'Eko Wijaya',
                'gender' => 'Pria',
                'departement' => 'Security',
                'workYears' => '2024',
                'employeementStatus' => 'Kontrak',
                'role' => 'employee',
                'status' => 'Tidak Aktif',
            ],
            [
                'alternatif' => 'A12',
                'username' => 'Ninda2019',
                'email' => 'ninda.zasmi@example.com',
                'password' => bcrypt('Ninda2019'),
                'fullname' => 'Ninda Zasmi A.',
                'gender' => 'Wanita',
                'departement' => 'Front Desk Office',
                'workYears' => '2019',
                'employeementStatus' => 'Tetap',
                'role' => 'employee',
                'status' => 'Tidak Aktif',
            ],
            [
                'alternatif' => 'A13',
                'username' => 'Ikadek2018',
                'email' => 'ikadek.sukeheriawan@example.com',
                'password' => bcrypt('Ikadek2018'),
                'fullname' => 'Ikadek Sukeheriawan',
                'gender' => 'Pria',
                'departement' => 'Front Desk Office',
                'workYears' => '2018',
                'employeementStatus' => 'Tetap',
                'role' => 'employee',
                'status' => 'Tidak Aktif',
            ],
            [
                'alternatif' => 'A14',
                'username' => 'Faras2018',
                'email' => 'faras.nabilla@example.com',
                'password' => bcrypt('Faras2018'),
                'fullname' => 'Faras Nabilla',
                'gender' => 'Wanita',
                'departement' => 'Front Desk Office',
                'workYears' => '2018',
                'employeementStatus' => 'Tetap',
                'role' => 'employee',
                'status' => 'Tidak Aktif',
            ],
            [
                'alternatif' => 'A15',
                'username' => 'Effendi2024',
                'email' => 'm.effendi@example.com',
                'password' => bcrypt('Effendi2024'),
                'fullname' => 'M. Effendi',
                'gender' => 'Pria',
                'departement' => 'Front Desk Office',
                'workYears' => '2024',
                'employeementStatus' => 'Tetap',
                'role' => 'employee',
                'status' => 'Tidak Aktif',
            ],
            [
                'alternatif' => 'A16',
                'username' => 'Nurul2022',
                'email' => 'nurul.hidayah@example.com',
                'password' => bcrypt('Nurul2022'),
                'fullname' => 'Nurul Hidayah',
                'gender' => 'Wanita',
                'departement' => 'Front Desk Office',
                'workYears' => '2022',
                'employeementStatus' => 'Kontrak',
                'role' => 'employee',
                'status' => 'Tidak Aktif',
            ],
            [
                'alternatif' => 'A17',
                'username' => 'Nugroho2023',
                'email' => 'nugroho.wibowo@example.com',
                'password' => bcrypt('Nugroho2023'),
                'fullname' => 'Nugroho Wibowo',
                'gender' => 'Pria',
                'departement' => 'Front Desk Office',
                'workYears' => '2023',
                'employeementStatus' => 'Kontrak',
                'role' => 'employee',
                'status' => 'Tidak Aktif',
            ],
            [
                'alternatif' => 'A18',
                'username' => 'Prasetyo2023',
                'email' => 'prasetyo.utomo@example.com',
                'password' => bcrypt('Prasetyo2023'),
                'fullname' => 'Prasetyo Utomo',
                'gender' => 'Pria',
                'departement' => 'Front Desk Office',
                'workYears' => '2023',
                'employeementStatus' => 'Kontrak',
                'role' => 'employee',
                'status' => 'Tidak Aktif',
            ],
            [
                'alternatif' => 'A19',
                'username' => 'Gita2023',
                'email' => 'gita.maharani@example.com',
                'password' => bcrypt('Gita2023'),
                'fullname' => 'Gita Maharani',
                'gender' => 'Wanita',
                'departement' => 'Front Desk Office',
                'workYears' => '2023',
                'employeementStatus' => 'Kontrak',
                'role' => 'employee',
                'status' => 'Tidak Aktif',
            ],
            [
                'alternatif' => 'A20',
                'username' => 'Lukman2020',
                'email' => 'lukman.hakim@example.com',
                'password' => bcrypt('Lukman2020'),
                'fullname' => 'Lukman Hakim',
                'gender' => 'Pria',
                'departement' => 'General Maintenance',
                'workYears' => '2020',
                'employeementStatus' => 'Tetap',
                'role' => 'employee',
                'status' => 'Tidak Aktif',
            ],
            [
                'alternatif' => 'A21',
                'username' => 'Juli2023',
                'email' => 'juli.astuti@example.com',
                'password' => bcrypt('Juli2023'),
                'fullname' => 'Juli Astuti Rahayu',
                'gender' => 'Wanita',
                'departement' => 'General Maintenance',
                'workYears' => '2023',
                'employeementStatus' => 'Kontrak',
                'role' => 'employee',
                'status' => 'Tidak Aktif',
            ],
            [
                'alternatif' => 'A22',
                'username' => 'Kartika2024',
                'email' => 'kartika.wijaya@example.com',
                'password' => bcrypt('Kartika2024'),
                'fullname' => 'Kartika Wijaya',
                'gender' => 'Wanita',
                'departement' => 'General Maintenance',
                'workYears' => '2024',
                'employeementStatus' => 'Kontrak',
                'role' => 'employee',
                'status' => 'Tidak Aktif',
            ],
            [
                'alternatif' => 'A23',
                'username' => 'Rizal2024',
                'email' => 'rizal.saputra@example.com',
                'password' => bcrypt('Rizal2024'),
                'fullname' => 'Rizal Dwi Saputra',
                'gender' => 'Pria',
                'departement' => 'General Maintenance',
                'workYears' => '2024',
                'employeementStatus' => 'Kontrak',
                'role' => 'employee',
                'status' => 'Tidak Aktif',
            ],
            [
                'alternatif' => 'A24',
                'username' => 'Siti2018',
                'email' => 'siti.desi@example.com',
                'password' => bcrypt('Siti2018'),
                'fullname' => 'Siti Desi Fadillah',
                'gender' => 'Wanita',
                'departement' => 'Housekeeping',
                'workYears' => '2018',
                'employeementStatus' => 'Tetap',
                'role' => 'employee',
                'status' => 'Tidak Aktif',
            ],
            [
                'alternatif' => 'A25',
                'username' => 'Andi2020',
                'email' => 'andi.permana@example.com',
                'password' => bcrypt('Andi2020'),
                'fullname' => 'Andi Bagus Permana',
                'gender' => 'Pria',
                'departement' => 'Housekeeping',
                'workYears' => '2020',
                'employeementStatus' => 'Tetap',
                'role' => 'employee',
                'status' => 'Tidak Aktif',
            ],
            [
                'alternatif' => 'A26',
                'username' => 'Arif2020',
                'email' => 'arif.hakim@example.com',
                'password' => bcrypt('Arif2020'),
                'fullname' => 'Arif Rahman Hakim',
                'gender' => 'Pria',
                'departement' => 'Housekeeping',
                'workYears' => '2020',
                'employeementStatus' => 'Kontrak',
                'role' => 'employee',
                'status' => 'Tidak Aktif',
            ],
            [
                'alternatif' => 'A27',
                'username' => 'Mira2022',
                'email' => 'mira.santoso@example.com',
                'password' => bcrypt('Mira2022'),
                'fullname' => 'Mira Santoso',
                'gender' => 'Wanita',
                'departement' => 'Housekeeping',
                'workYears' => '2022',
                'employeementStatus' => 'Kontrak',
                'role' => 'employee',
                'status' => 'Tidak Aktif',
            ],
            [
                'alternatif' => 'A28',
                'username' => 'Rudi2023',
                'email' => 'rudi.hermawan@example.com',
                'password' => bcrypt('Rudi2023'),
                'fullname' => 'Rudi Hermawan Ramdani',
                'gender' => 'Pria',
                'departement' => 'Housekeeping',
                'workYears' => '2023',
                'employeementStatus' => 'Kontrak',
                'role' => 'employee',
                'status' => 'Tidak Aktif',
            ],
            [
                'alternatif' => 'A29',
                'username' => 'Surya2023',
                'email' => 'surya.darmawan@example.com',
                'password' => bcrypt('Surya2023'),
                'fullname' => 'Surya Darmawan',
                'gender' => 'Pria',
                'departement' => 'Housekeeping',
                'workYears' => '2023',
                'employeementStatus' => 'Kontrak',
                'role' => 'employee',
                'status' => 'Tidak Aktif',
            ],
            [
                'alternatif' => 'A30',
                'username' => 'Wahyu2024',
                'email' => 'wahyu.aditya@example.com',
                'password' => bcrypt('Wahyu2024'),
                'fullname' => 'Wahyu Aditya',
                'gender' => 'Pria',
                'departement' => 'Housekeeping',
                'workYears' => '2024',
                'employeementStatus' => 'Kontrak',
                'role' => 'employee',
                'status' => 'Tidak Aktif',
            ],
            [
                'alternatif' => 'A31',
                'username' => 'Teguh2024',
                'email' => 'teguh.riyadi@example.com',
                'password' => bcrypt('Teguh2024'),
                'fullname' => 'Teguh Riyadi',
                'gender' => 'Pria',
                'departement' => 'Housekeeping',
                'workYears' => '2024',
                'employeementStatus' => 'Kontrak',
                'role' => 'employee',
                'status' => 'Tidak Aktif',
            ],
            [
                'alternatif' => 'A32',
                'username' => 'Ahmad2024',
                'email' => 'ahmad.fauzi@example.com',
                'password' => bcrypt('Ahmad2024'),
                'fullname' => 'Ahmad Fauzi',
                'gender' => 'Pria',
                'departement' => 'Housekeeping',
                'workYears' => '2024',
                'employeementStatus' => 'Kontrak',
                'role' => 'employee',
                'status' => 'Tidak Aktif',
            ],
            [
                'alternatif' => 'A33',
                'username' => 'Yusuf2019',
                'email' => 'yusuf.budianto@example.com',
                'password' => bcrypt('Yusuf2019'),
                'fullname' => 'Yusuf Budianto',
                'gender' => 'Pria',
                'departement' => 'Sales Admin',
                'workYears' => '2019',
                'employeementStatus' => 'Tetap',
                'role' => 'employee',
                'status' => 'Tidak Aktif',
            ],
            [
                'alternatif' => 'A34',
                'username' => 'Okky2019',
                'email' => 'okky.pratama@example.com',
                'password' => bcrypt('Okky2019'),
                'fullname' => 'Okky Pratama Andriani',
                'gender' => 'Wanita',
                'departement' => 'Sales Admin',
                'workYears' => '2019',
                'employeementStatus' => 'Tetap',
                'role' => 'employee',
                'status' => 'Tidak Aktif',
            ],
            [
                'alternatif' => 'A35',
                'username' => 'Putri2023',
                'email' => 'putri.anggraeni@example.com',
                'password' => bcrypt('Putri2023'),
                'fullname' => 'Putri Anggraeni Lestari',
                'gender' => 'Wanita',
                'departement' => 'Sales Admin',
                'workYears' => '2023',
                'employeementStatus' => 'Kontrak',
                'role' => 'employee',
                'status' => 'Tidak Aktif',
            ],
            [
                'alternatif' => 'A36',
                'username' => 'Bambang2023',
                'email' => 'bambang.sudrajat@example.com',
                'password' => bcrypt('Bambang2023'),
                'fullname' => 'Bambang Sudrajat',
                'gender' => 'Pria',
                'departement' => 'Sales Admin',
                'workYears' => '2023',
                'employeementStatus' => 'Kontrak',
                'role' => 'employee',
                'status' => 'Tidak Aktif',
            ],
            [
                'alternatif' => 'A37',
                'username' => 'Nia2024',
                'email' => 'nia.kurniawati@example.com',
                'password' => bcrypt('Nia2024'),
                'fullname' => 'Nia Kurniawati',
                'gender' => 'Wanita',
                'departement' => 'Sales Admin',
                'workYears' => '2024',
                'employeementStatus' => 'Kontrak',
                'role' => 'employee',
                'status' => 'Tidak Aktif',
            ],
            [
                'alternatif' => 'A38',
                'username' => 'Gito2017',
                'email' => 'gito.wibowo@example.com',
                'password' => bcrypt('Gito2017'),
                'fullname' => 'Gito Wibowo',
                'gender' => 'Pria',
                'departement' => 'F&B Service',
                'workYears' => '2017',
                'employeementStatus' => 'Tetap',
                'role' => 'employee',
                'status' => 'Tidak Aktif',
            ],
            [
                'alternatif' => 'A39',
                'username' => 'Hendra2017',
                'email' => 'hendra.gunawan@example.com',
                'password' => bcrypt('Hendra2017'),
                'fullname' => 'Hendra Gunawan',
                'gender' => 'Pria',
                'departement' => 'F&B Service',
                'workYears' => '2017',
                'employeementStatus' => 'Tetap',
                'role' => 'employee',
                'status' => 'Tidak Aktif',
            ],
            [
                'alternatif' => 'A40',
                'username' => 'Winda2019',
                'email' => 'winda.yuliana@example.com',
                'password' => bcrypt('Winda2019'),
                'fullname' => 'Winda Yuliana',
                'gender' => 'Wanita',
                'departement' => 'F&B Service',
                'workYears' => '2019',
                'employeementStatus' => 'Tetap',
                'role' => 'employee',
                'status' => 'Tidak Aktif',
            ],
            [
                'alternatif' => 'A41',
                'username' => 'Eka2022',
                'email' => 'eka.suryana@example.com',
                'password' => bcrypt('Eka2022'),
                'fullname' => 'Eka Suryana',
                'gender' => 'Pria',
                'departement' => 'F&B Service',
                'workYears' => '2022',
                'employeementStatus' => 'Kontrak',
                'role' => 'employee',
                'status' => 'Tidak Aktif',
            ],
            [
                'alternatif' => 'A42',
                'username' => 'Fandi2023',
                'email' => 'fandi.kurniawan@example.com',
                'password' => bcrypt('Fandi2023'),
                'fullname' => 'Fandi Kurniawan',
                'gender' => 'Pria',
                'departement' => 'F&B Service',
                'workYears' => '2023',
                'employeementStatus' => 'Kontrak',
                'role' => 'employee',
                'status' => 'Tidak Aktif',
            ],
            [
                'alternatif' => 'A43',
                'username' => 'Iwan2023',
                'email' => 'iwan.sutrisno@example.com',
                'password' => bcrypt('Iwan2023'),
                'fullname' => 'Iwan Sutrisno',
                'gender' => 'Pria',
                'departement' => 'F&B Service',
                'workYears' => '2023',
                'employeementStatus' => 'Kontrak',
                'role' => 'employee',
                'status' => 'Tidak Aktif',
            ],
            [
                'alternatif' => 'A44',
                'username' => 'Citra2024',
                'email' => 'citra.novia@example.com',
                'password' => bcrypt('Citra2024'),
                'fullname' => 'Citra Novia',
                'gender' => 'Wanita',
                'departement' => 'F&B Service',
                'workYears' => '2024',
                'employeementStatus' => 'Kontrak',
                'role' => 'employee',
                'status' => 'Tidak Aktif',
            ],
            [
                'alternatif' => 'A45',
                'username' => 'Desi2024',
                'email' => 'desi.aprilia@example.com',
                'password' => bcrypt('Desi2024'),
                'fullname' => 'Desi Aprilia Sari',
                'gender' => 'Wanita',
                'departement' => 'F&B Service',
                'workYears' => '2024',
                'employeementStatus' => 'Kontrak',
                'role' => 'employee',
                'status' => 'Tidak Aktif',
            ],
            [
                'alternatif' => 'A46',
                'username' => 'Maman2019',
                'email' => 'maman.suherman@example.com',
                'password' => bcrypt('Maman2019'),
                'fullname' => 'Maman Suherman',
                'gender' => 'Pria',
                'departement' => 'F&B Product',
                'workYears' => '2019',
                'employeementStatus' => 'Tetap',
                'role' => 'employee',
                'status' => 'Tidak Aktif',
            ],
            [
                'alternatif' => 'A47',
                'username' => 'Rina2023',
                'email' => 'rina.handayani@example.com',
                'password' => bcrypt('Rina2023'),
                'fullname' => 'Rina Handayani',
                'gender' => 'Wanita',
                'departement' => 'F&B Product',
                'workYears' => '2023',
                'employeementStatus' => 'Kontrak',
                'role' => 'employee',
                'status' => 'Tidak Aktif',
            ],
            [
                'alternatif' => 'A48',
                'username' => 'Joni2023',
                'email' => 'joni.prakoso@example.com',
                'password' => bcrypt('Joni2023'),
                'fullname' => 'Joni Prakoso',
                'gender' => 'Pria',
                'departement' => 'F&B Product',
                'workYears' => '2023',
                'employeementStatus' => 'Kontrak',
                'role' => 'employee',
                'status' => 'Tidak Aktif',
            ],
            [
                'alternatif' => 'A49',
                'username' => 'Fikri2024',
                'email' => 'fikri.maulana@example.com',
                'password' => bcrypt('Fikri2024'),
                'fullname' => 'Fikri Maulana',
                'gender' => 'Pria',
                'departement' => 'F&B Product',
                'workYears' => '2024',
                'employeementStatus' => 'Kontrak',
                'role' => 'employee',
                'status' => 'Tidak Aktif',
            ],
            [
                'alternatif' => 'A50',
                'username' => 'Luki2024',
                'email' => 'luki.setiawan@example.com',
                'password' => bcrypt('Luki2024'),
                'fullname' => 'Luki Setiawan Ramdani',
                'gender' => 'Pria',
                'departement' => 'F&B Product',
                'workYears' => '2024',
                'employeementStatus' => 'Kontrak',
                'role' => 'employee',
                'status' => 'Tidak Aktif',
            ],
            [
                'alternatif' => 'A51',
                'username' => 'Sri2024',
                'email' => 'sri.utami@example.com',
                'password' => bcrypt('Sri2024'),
                'fullname' => 'Sri Utami Lestari',
                'gender' => 'Wanita',
                'departement' => 'F&B Product',
                'workYears' => '2024',
                'employeementStatus' => 'Kontrak',
                'role' => 'employee',
                'status' => 'Tidak Aktif',
            ],
            [
                'alternatif' => 'A52',
                'username' => 'Variz2018',
                'email' => 'm.variz@example.com',
                'password' => bcrypt('Variz2018'),
                'fullname' => 'M. Variz Rheza',
                'gender' => 'Pria',
                'departement' => 'Cook',
                'workYears' => '2018',
                'employeementStatus' => 'Tetap',
                'role' => 'employee',
                'status' => 'Tidak Aktif',
            ],
            [
                'alternatif' => 'A53',
                'username' => 'Ikmal2020',
                'email' => 'ikmal.fahreza@example.com',
                'password' => bcrypt('Ikmal2020'),
                'fullname' => 'Ikmal Fahreza',
                'gender' => 'Pria',
                'departement' => 'Cook',
                'workYears' => '2020',
                'employeementStatus' => 'Tetap',
                'role' => 'employee',
                'status' => 'Tidak Aktif',
            ],
            [
                'alternatif' => 'A54',
                'username' => 'Yogi2019',
                'email' => 'yogi.fadilah@example.com',
                'password' => bcrypt('Yogi2019'),
                'fullname' => 'Yogi Fadilah Ramdhani',
                'gender' => 'Pria',
                'departement' => 'Cook',
                'workYears' => '2019',
                'employeementStatus' => 'Tetap',
                'role' => 'employee',
                'status' => 'Tidak Aktif',
            ],
            [
                'alternatif' => 'A55',
                'username' => 'Tina2018',
                'email' => 'tina.wulandari@example.com',
                'password' => bcrypt('Tina2018'),
                'fullname' => 'Tina Dwi Wulandari',
                'gender' => 'Wanita',
                'departement' => 'Cook',
                'workYears' => '2018',
                'employeementStatus' => 'Tetap',
                'role' => 'employee',
                'status' => 'Tidak Aktif',
            ],
            [
                'alternatif' => 'A56',
                'username' => 'Fahri2022',
                'email' => 'fahri.indawirawan@example.com',
                'password' => bcrypt('Fahri2022'),
                'fullname' => 'Fahri Indawirawan',
                'gender' => 'Pria',
                'departement' => 'Cook',
                'workYears' => '2022',
                'employeementStatus' => 'Kontrak',
                'role' => 'employee',
                'status' => 'Tidak Aktif',
            ],
            [
                'alternatif' => 'A57',
                'username' => 'Sandi2023',
                'email' => 'sandi.yudha@example.com',
                'password' => bcrypt('Sandi2023'),
                'fullname' => 'Sandi Yudha',
                'gender' => 'Pria',
                'departement' => 'Cook',
                'workYears' => '2023',
                'employeementStatus' => 'Kontrak',
                'role' => 'employee',
                'status' => 'Tidak Aktif',
            ],
            [
                'alternatif' => 'A58',
                'username' => 'Fajar2024',
                'email' => 'fajar.nugroho@example.com',
                'password' => bcrypt('Fajar2024'),
                'fullname' => 'Fajar Nugroho',
                'gender' => 'Pria',
                'departement' => 'Cook',
                'workYears' => '2024',
                'employeementStatus' => 'Kontrak',
                'role' => 'employee',
                'status' => 'Tidak Aktif',
            ],
            [
                'alternatif' => 'A59',
                'username' => 'Amalia2024',
                'email' => 'amalia.fitriani@example.com',
                'password' => bcrypt('Amalia2024'),
                'fullname' => 'Amalia Fitriani Rahayu',
                'gender' => 'Wanita',
                'departement' => 'Cook',
                'workYears' => '2024',
                'employeementStatus' => 'Kontrak',
                'role' => 'employee',
                'status' => 'Tidak Aktif',
            ],
            [
                'alternatif' => 'A60',
                'username' => 'Nando2024',
                'email' => 'nando.pratama@example.com',
                'password' => bcrypt('Nando2024'),
                'fullname' => 'Nando Pratama',
                'gender' => 'Pria',
                'departement' => 'Cook',
                'workYears' => '2024',
                'employeementStatus' => 'Kontrak',
                'role' => 'employee',
                'status' => 'Tidak Aktif',
            ],
        ];
        foreach ($employeeDataList as $employeeData) {
            User::create([
                'alternatif' => $employeeData['alternatif'],
                'username' => $employeeData['username'],
                'email' => $employeeData['email'],
                'password' => $employeeData['password'],
                'fullname' => $employeeData['fullname'],
                'gender' => $employeeData['gender'],
                'departement' => $employeeData['departement'],
                'workYears' => $employeeData['workYears'],
                'employeementStatus' => $employeeData['employeementStatus'],
                'role' => $employeeData['role'],
                'status' => $employeeData['status'],
            ]);
        }
    }
}
