<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class EvaluationEmployeeDataSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $evaluationEmployeeData = [

            //======== Tahap 1 ========
            [
                'alternatif' => 'A4',
                'fullname' => 'Anggi Dewi Melati',
                'email' => 'anggi.dewi@example.com',
                'departement' => 'Account Receivable',
                'employeementStatus' => 'Kontrak',
                'evaluation_years' => '2024',
                'evaluation_stage' => 'T1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif' => 'A5',
                'fullname' => 'Bunga Ayu Lestari',
                'email' => 'bunga.ayu@example.com',
                'departement' => 'Account Receivable',
                'employeementStatus' => 'Kontrak',
                'evaluation_years' => '2024',
                'evaluation_stage' => 'T1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif' => 'A8',
                'fullname' => 'Joko Susilo Hartono',
                'email' => 'joko.susilo@example.com',
                'departement' => 'Security',
                'employeementStatus' => 'Kontrak',
                'evaluation_years' => '2024',
                'evaluation_stage' => 'T1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif' => 'A9',
                'fullname' => 'Eko Putra Ramdani',
                'email' => 'eko.putra@example.com',
                'departement' => 'Security',
                'employeementStatus' => 'Kontrak',
                'evaluation_years' => '2024',
                'evaluation_stage' => 'T1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif' => 'A18',
                'fullname' => 'Prasetyo Utomo',
                'email' => 'prasetyo.utomo@example.com',
                'departement' => 'Front Desk Office',
                'employeementStatus' => 'Kontrak',
                'evaluation_years' => '2024',
                'evaluation_stage' => 'T1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif' => 'A19',
                'fullname' => 'Gita Maharani',
                'email' => 'gita.maharani@example.com',
                'departement' => 'Front Desk Office',
                'employeementStatus' => 'Kontrak',
                'evaluation_years' => '2024',
                'evaluation_stage' => 'T1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif' => 'A22',
                'fullname' => 'Kartika Wijaya',
                'email' => 'kartika.wijaya@example.com',
                'departement' => 'General Maintenance',
                'employeementStatus' => 'Kontrak',
                'evaluation_years' => '2024',
                'evaluation_stage' => 'T1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif' => 'A23',
                'fullname' => 'Rizal Dwi Saputra',
                'email' => 'rizal.saputra@example.com',
                'departement' => 'General Maintenance',
                'employeementStatus' => 'Kontrak',
                'evaluation_years' => '2024',
                'evaluation_stage' => 'T1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif' => 'A29',
                'fullname' => 'Surya Darmawan',
                'email' => 'surya.darmawan@example.com',
                'departement' => 'Housekeeping',
                'employeementStatus' => 'Kontrak',
                'evaluation_years' => '2024',
                'evaluation_stage' => 'T1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif' => 'A30',
                'fullname' => 'Wahyu Aditya',
                'email' => 'wahyu.aditya@example.com',
                'departement' => 'Housekeeping',
                'employeementStatus' => 'Kontrak',
                'evaluation_years' => '2024',
                'evaluation_stage' => 'T1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif' => 'A31',
                'fullname' => 'Teguh Riyadi',
                'email' => 'teguh.riyadi@example.com',
                'departement' => 'Housekeeping',
                'employeementStatus' => 'Kontrak',
                'evaluation_years' => '2024',
                'evaluation_stage' => 'T1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif' => 'A35',
                'fullname' => 'Putri Anggraeni Lestari',
                'email' => 'putri.anggraeni@example.com',
                'departement' => 'Sales Admin',
                'employeementStatus' => 'Kontrak',
                'evaluation_years' => '2024',
                'evaluation_stage' => 'T1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif' => 'A36',
                'fullname' => 'Bambang Sudrajat',
                'email' => 'bambang.sudrajat@example.com',
                'departement' => 'Sales Admin',
                'employeementStatus' => 'Kontrak',
                'evaluation_years' => '2024',
                'evaluation_stage' => 'T1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif' => 'A43',
                'fullname' => 'Iwan Sutrisno',
                'email' => 'iwan.sutrisno@example.com',
                'departement' => 'F&B Service',
                'employeementStatus' => 'Kontrak',
                'evaluation_years' => '2024',
                'evaluation_stage' => 'T1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif' => 'A45',
                'fullname' => 'Desi Aprilia Sari',
                'email' => 'desi.aprilia@example.com',
                'departement' => 'F&B Service',
                'employeementStatus' => 'Kontrak',
                'evaluation_years' => '2024',
                'evaluation_stage' => 'T1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif' => 'A50',
                'fullname' => 'Luki Setiawan Ramdani',
                'email' => 'luki.setiawan@example.com',
                'departement' => 'F&B Product',
                'employeementStatus' => 'Kontrak',
                'evaluation_years' => '2024',
                'evaluation_stage' => 'T1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif' => 'A51',
                'fullname' => 'Sri Utami Lestari',
                'email' => 'sri.utami@example.com',
                'departement' => 'F&B Product',
                'employeementStatus' => 'Kontrak',
                'evaluation_years' => '2024',
                'evaluation_stage' => 'T1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif' => 'A57',
                'fullname' => 'Sandi Yudha',
                'email' => 'sandi.yudha@example.com',
                'departement' => 'Cook',
                'employeementStatus' => 'Kontrak',
                'evaluation_years' => '2024',
                'evaluation_stage' => 'T1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif' => 'A58',
                'fullname' => 'Fajar Nugroho',
                'email' => 'fajar.nugroho@example.com',
                'departement' => 'Cook',
                'employeementStatus' => 'Kontrak',
                'evaluation_years' => '2024',
                'evaluation_stage' => 'T1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif' => 'A59',
                'fullname' => 'Amalia Fitriani Rahayu',
                'email' => 'amalia.fitriani@example.com',
                'departement' => 'Cook',
                'employeementStatus' => 'Kontrak',
                'evaluation_years' => '2024',
                'evaluation_stage' => 'T1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            //======== Tahap 2 ========
            [
                'alternatif' => 'A4',
                'fullname' => 'Anggi Dewi Melati',
                'email' => 'anggi.dewi@example.com',
                'departement' => 'Account Receivable',
                'employeementStatus' => 'Kontrak',
                'evaluation_years' => '2024',
                'evaluation_stage' => 'T2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif' => 'A5',
                'fullname' => 'Bunga Ayu Lestari',
                'email' => 'bunga.ayu@example.com',
                'departement' => 'Account Receivable',
                'employeementStatus' => 'Kontrak',
                'evaluation_years' => '2024',
                'evaluation_stage' => 'T2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif' => 'A8',
                'fullname' => 'Joko Susilo Hartono',
                'email' => 'joko.susilo@example.com',
                'departement' => 'Security',
                'employeementStatus' => 'Kontrak',
                'evaluation_years' => '2024',
                'evaluation_stage' => 'T2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif' => 'A9',
                'fullname' => 'Eko Putra Ramdani',
                'email' => 'eko.putra@example.com',
                'departement' => 'Security',
                'employeementStatus' => 'Kontrak',
                'evaluation_years' => '2024',
                'evaluation_stage' => 'T2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif' => 'A18',
                'fullname' => 'Prasetyo Utomo',
                'email' => 'prasetyo.utomo@example.com',
                'departement' => 'Front Desk Office',
                'employeementStatus' => 'Kontrak',
                'evaluation_years' => '2024',
                'evaluation_stage' => 'T2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif' => 'A19',
                'fullname' => 'Gita Maharani',
                'email' => 'gita.maharani@example.com',
                'departement' => 'Front Desk Office',
                'employeementStatus' => 'Kontrak',
                'evaluation_years' => '2024',
                'evaluation_stage' => 'T2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif' => 'A22',
                'fullname' => 'Kartika Wijaya',
                'email' => 'kartika.wijaya@example.com',
                'departement' => 'General Maintenance',
                'employeementStatus' => 'Kontrak',
                'evaluation_years' => '2024',
                'evaluation_stage' => 'T2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif' => 'A23',
                'fullname' => 'Rizal Dwi Saputra',
                'email' => 'rizal.saputra@example.com',
                'departement' => 'General Maintenance',
                'employeementStatus' => 'Kontrak',
                'evaluation_years' => '2024',
                'evaluation_stage' => 'T2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif' => 'A29',
                'fullname' => 'Surya Darmawan',
                'email' => 'surya.darmawan@example.com',
                'departement' => 'Housekeeping',
                'employeementStatus' => 'Kontrak',
                'evaluation_years' => '2024',
                'evaluation_stage' => 'T2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif' => 'A30',
                'fullname' => 'Wahyu Aditya',
                'email' => 'wahyu.aditya@example.com',
                'departement' => 'Housekeeping',
                'employeementStatus' => 'Kontrak',
                'evaluation_years' => '2024',
                'evaluation_stage' => 'T2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif' => 'A31',
                'fullname' => 'Teguh Riyadi',
                'email' => 'teguh.riyadi@example.com',
                'departement' => 'Housekeeping',
                'employeementStatus' => 'Kontrak',
                'evaluation_years' => '2024',
                'evaluation_stage' => 'T2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif' => 'A35',
                'fullname' => 'Putri Anggraeni Lestari',
                'email' => 'putri.anggraeni@example.com',
                'departement' => 'Sales Admin',
                'employeementStatus' => 'Kontrak',
                'evaluation_years' => '2024',
                'evaluation_stage' => 'T2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif' => 'A36',
                'fullname' => 'Bambang Sudrajat',
                'email' => 'bambang.sudrajat@example.com',
                'departement' => 'Sales Admin',
                'employeementStatus' => 'Kontrak',
                'evaluation_years' => '2024',
                'evaluation_stage' => 'T2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif' => 'A43',
                'fullname' => 'Iwan Sutrisno',
                'email' => 'iwan.sutrisno@example.com',
                'departement' => 'F&B Service',
                'employeementStatus' => 'Kontrak',
                'evaluation_years' => '2024',
                'evaluation_stage' => 'T2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif' => 'A45',
                'fullname' => 'Desi Aprilia Sari',
                'email' => 'desi.aprilia@example.com',
                'departement' => 'F&B Service',
                'employeementStatus' => 'Kontrak',
                'evaluation_years' => '2024',
                'evaluation_stage' => 'T2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif' => 'A50',
                'fullname' => 'Luki Setiawan Ramdani',
                'email' => 'luki.setiawan@example.com',
                'departement' => 'F&B Product',
                'employeementStatus' => 'Kontrak',
                'evaluation_years' => '2024',
                'evaluation_stage' => 'T2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif' => 'A51',
                'fullname' => 'Sri Utami Lestari',
                'email' => 'sri.utami@example.com',
                'departement' => 'F&B Product',
                'employeementStatus' => 'Kontrak',
                'evaluation_years' => '2024',
                'evaluation_stage' => 'T2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif' => 'A57',
                'fullname' => 'Sandi Yudha',
                'email' => 'sandi.yudha@example.com',
                'departement' => 'Cook',
                'employeementStatus' => 'Kontrak',
                'evaluation_years' => '2024',
                'evaluation_stage' => 'T2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif' => 'A58',
                'fullname' => 'Fajar Nugroho',
                'email' => 'fajar.nugroho@example.com',
                'departement' => 'Cook',
                'employeementStatus' => 'Kontrak',
                'evaluation_years' => '2024',
                'evaluation_stage' => 'T2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif' => 'A59',
                'fullname' => 'Amalia Fitriani Rahayu',
                'email' => 'amalia.fitriani@example.com',
                'departement' => 'Cook',
                'employeementStatus' => 'Kontrak',
                'evaluation_years' => '2024',
                'evaluation_stage' => 'T2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            //======== Tahap 3 =======
            [
                'alternatif' => 'A4',
                'fullname' => 'Anggi Dewi Melati',
                'email' => 'anggi.dewi@example.com',
                'departement' => 'Account Receivable',
                'employeementStatus' => 'Kontrak',
                'evaluation_years' => '2024',
                'evaluation_stage' => 'T3',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif' => 'A5',
                'fullname' => 'Bunga Ayu Lestari',
                'email' => 'bunga.ayu@example.com',
                'departement' => 'Account Receivable',
                'employeementStatus' => 'Kontrak',
                'evaluation_years' => '2024',
                'evaluation_stage' => 'T3',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif' => 'A8',
                'fullname' => 'Joko Susilo Hartono',
                'email' => 'joko.susilo@example.com',
                'departement' => 'Security',
                'employeementStatus' => 'Kontrak',
                'evaluation_years' => '2024',
                'evaluation_stage' => 'T3',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif' => 'A9',
                'fullname' => 'Eko Putra Ramdani',
                'email' => 'eko.putra@example.com',
                'departement' => 'Security',
                'employeementStatus' => 'Kontrak',
                'evaluation_years' => '2024',
                'evaluation_stage' => 'T3',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif' => 'A18',
                'fullname' => 'Prasetyo Utomo',
                'email' => 'prasetyo.utomo@example.com',
                'departement' => 'Front Desk Office',
                'employeementStatus' => 'Kontrak',
                'evaluation_years' => '2024',
                'evaluation_stage' => 'T3',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif' => 'A19',
                'fullname' => 'Gita Maharani',
                'email' => 'gita.maharani@example.com',
                'departement' => 'Front Desk Office',
                'employeementStatus' => 'Kontrak',
                'evaluation_years' => '2024',
                'evaluation_stage' => 'T3',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif' => 'A22',
                'fullname' => 'Kartika Wijaya',
                'email' => 'kartika.wijaya@example.com',
                'departement' => 'General Maintenance',
                'employeementStatus' => 'Kontrak',
                'evaluation_years' => '2024',
                'evaluation_stage' => 'T3',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif' => 'A23',
                'fullname' => 'Rizal Dwi Saputra',
                'email' => 'rizal.saputra@example.com',
                'departement' => 'General Maintenance',
                'employeementStatus' => 'Kontrak',
                'evaluation_years' => '2024',
                'evaluation_stage' => 'T3',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif' => 'A29',
                'fullname' => 'Surya Darmawan',
                'email' => 'surya.darmawan@example.com',
                'departement' => 'Housekeeping',
                'employeementStatus' => 'Kontrak',
                'evaluation_years' => '2024',
                'evaluation_stage' => 'T3',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif' => 'A30',
                'fullname' => 'Wahyu Aditya',
                'email' => 'wahyu.aditya@example.com',
                'departement' => 'Housekeeping',
                'employeementStatus' => 'Kontrak',
                'evaluation_years' => '2024',
                'evaluation_stage' => 'T3',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif' => 'A31',
                'fullname' => 'Teguh Riyadi',
                'email' => 'teguh.riyadi@example.com',
                'departement' => 'Housekeeping',
                'employeementStatus' => 'Kontrak',
                'evaluation_years' => '2024',
                'evaluation_stage' => 'T3',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif' => 'A35',
                'fullname' => 'Putri Anggraeni Lestari',
                'email' => 'putri.anggraeni@example.com',
                'departement' => 'Sales Admin',
                'employeementStatus' => 'Kontrak',
                'evaluation_years' => '2024',
                'evaluation_stage' => 'T3',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif' => 'A36',
                'fullname' => 'Bambang Sudrajat',
                'email' => 'bambang.sudrajat@example.com',
                'departement' => 'Sales Admin',
                'employeementStatus' => 'Kontrak',
                'evaluation_years' => '2024',
                'evaluation_stage' => 'T3',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif' => 'A43',
                'fullname' => 'Iwan Sutrisno',
                'email' => 'iwan.sutrisno@example.com',
                'departement' => 'F&B Service',
                'employeementStatus' => 'Kontrak',
                'evaluation_years' => '2024',
                'evaluation_stage' => 'T3',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif' => 'A45',
                'fullname' => 'Desi Aprilia Sari',
                'email' => 'desi.aprilia@example.com',
                'departement' => 'F&B Service',
                'employeementStatus' => 'Kontrak',
                'evaluation_years' => '2024',
                'evaluation_stage' => 'T3',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif' => 'A50',
                'fullname' => 'Luki Setiawan Ramdani',
                'email' => 'luki.setiawan@example.com',
                'departement' => 'F&B Product',
                'employeementStatus' => 'Kontrak',
                'evaluation_years' => '2024',
                'evaluation_stage' => 'T3',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif' => 'A51',
                'fullname' => 'Sri Utami Lestari',
                'email' => 'sri.utami@example.com',
                'departement' => 'F&B Product',
                'employeementStatus' => 'Kontrak',
                'evaluation_years' => '2024',
                'evaluation_stage' => 'T3',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif' => 'A57',
                'fullname' => 'Sandi Yudha',
                'email' => 'sandi.yudha@example.com',
                'departement' => 'Cook',
                'employeementStatus' => 'Kontrak',
                'evaluation_years' => '2024',
                'evaluation_stage' => 'T3',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif' => 'A58',
                'fullname' => 'Fajar Nugroho',
                'email' => 'fajar.nugroho@example.com',
                'departement' => 'Cook',
                'employeementStatus' => 'Kontrak',
                'evaluation_years' => '2024',
                'evaluation_stage' => 'T3',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'alternatif' => 'A59',
                'fullname' => 'Amalia Fitriani Rahayu',
                'email' => 'amalia.fitriani@example.com',
                'departement' => 'Cook',
                'employeementStatus' => 'Kontrak',
                'evaluation_years' => '2024',
                'evaluation_stage' => 'T3',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // ======= Tahap 4 ======= (opsional)
        ];
        foreach ($evaluationEmployeeData as $data) {
            DB::table('evaluation_employee_data')->updateOrInsert(
                [
                    'email' => $data['email'],
                    'evaluation_years' => $data['evaluation_years'],
                    'evaluation_stage' => $data['evaluation_stage'], // harus ditambahkan di kondisi pencarian
                ],
                [
                    'alternatif'         => $data['alternatif'],
                    'fullname'           => $data['fullname'],
                    'departement'        => $data['departement'],
                    'employeementStatus' => $data['employeementStatus'],
                    'created_at'         => now(),
                    'updated_at'         => now(),
                ]
            );
        }
    }
}
