<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\DB;
use App\Http\Helpers\EvaluationProcessor;
use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class EvaluationT3Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $targetStage = 't3';
        $evaluationList = [
            'Anggi Dewi Melati' => [
                'alternatif' => 'A4',
                'C1' => 80,
                'C2' => 60,
                'C3' => 80,
                'C4' => 80,
                'C5' => 60,
                'C6' => 100,
                'C7' => 60,
                'C8' => 80,
                'C9' => 80,
                'C10' => 100,
                'C11' => 80,
                'C12' => 100,
                'C13' => 60,
                'C14' => 80,
                'C15' => 80,
            ],
            'Bunga Ayu Lestari' => [
                'alternatif' => 'A5',
                'C1' => 80,
                'C2' => 60,
                'C3' => 60,
                'C4' => 80,
                'C5' => 80,
                'C6' => 60,
                'C7' => 80,
                'C8' => 60,
                'C9' => 80,
                'C10' => 60,
                'C11' => 60,
                'C12' => 80,
                'C13' => 60,
                'C14' => 80,
                'C15' => 60,
            ],
            'Joko Susilo Hartono' => [
                'alternatif' => 'A8',
                'C1' => 60,
                'C2' => 40,
                'C3' => 60,
                'C4' => 40,
                'C5' => 80,
                'C6' => 40,
                'C7' => 40,
                'C8' => 60,
                'C9' => 60,
                'C10' => 80,
                'C11' => 60,
                'C12' => 40,
                'C13' => 40,
                'C14' => 40,
                'C15' => 40,
            ],
            'Eko Putra Ramdani' => [
                'alternatif' => 'A9',
                'C1' => 60,
                'C2' => 80,
                'C3' => 60,
                'C4' => 60,
                'C5' => 80,
                'C6' => 80,
                'C7' => 60,
                'C8' => 60,
                'C9' => 60,
                'C10' => 100,
                'C11' => 60,
                'C12' => 60,
                'C13' => 60,
                'C14' => 100,
                'C15' => 80,
            ],
            'Prasetyo Utomo' => [
                'alternatif' => 'A18',
                'C1' => 60,
                'C2' => 60,
                'C3' => 100,
                'C4' => 80,
                'C5' => 60,
                'C6' => 60,
                'C7' => 60,
                'C8' => 80,
                'C9' => 100,
                'C10' => 60,
                'C11' => 80,
                'C12' => 80,
                'C13' => 60,
                'C14' => 60,
                'C15' => 80,
            ],
            'Gita Maharani' => [
                'alternatif' => 'A19',
                'C1' => 80,
                'C2' => 80,
                'C3' => 60,
                'C4' => 60,
                'C5' => 100,
                'C6' => 60,
                'C7' => 80,
                'C8' => 60,
                'C9' => 80,
                'C10' => 100,
                'C11' => 80,
                'C12' => 60,
                'C13' => 60,
                'C14' => 60,
                'C15' => 80,
            ],
            'Kartika Wijaya' => [
                'alternatif' => 'A22',
                'C1' => 80,
                'C2' => 100,
                'C3' => 80,
                'C4' => 60,
                'C5' => 60,
                'C6' => 80,
                'C7' => 80,
                'C8' => 100,
                'C9' => 100,
                'C10' => 60,
                'C11' => 80,
                'C12' => 100,
                'C13' => 60,
                'C14' => 80,
                'C15' => 80,
            ],
            'Rizal Dwi Saputra' => [
                'alternatif' => 'A23',
                'C1' => 80,
                'C2' => 60,
                'C3' => 60,
                'C4' => 60,
                'C5' => 80,
                'C6' => 60,
                'C7' => 60,
                'C8' => 60,
                'C9' => 80,
                'C10' => 60,
                'C11' => 60,
                'C12' => 80,
                'C13' => 60,
                'C14' => 80,
                'C15' => 60,
            ],
            'Surya Darmawan' => [
                'alternatif' => 'A29',
                'C1' => 60,
                'C2' => 60,
                'C3' => 60,
                'C4' => 60,
                'C5' => 100,
                'C6' => 80,
                'C7' => 60,
                'C8' => 60,
                'C9' => 80,
                'C10' => 60,
                'C11' => 80,
                'C12' => 60,
                'C13' => 80,
                'C14' => 60,
                'C15' => 60,
            ],
            'Wahyu Aditya' => [
                'alternatif' => 'A30',
                'C1' => 80,
                'C2' => 60,
                'C3' => 60,
                'C4' => 80,
                'C5' => 100,
                'C6' => 60,
                'C7' => 80,
                'C8' => 60,
                'C9' => 60,
                'C10' => 80,
                'C11' => 80,
                'C12' => 100,
                'C13' => 60,
                'C14' => 80,
                'C15' => 80,
            ],
            'Teguh Riyadi' => [
                'alternatif' => 'A31',
                'C1' => 80,
                'C2' => 80,
                'C3' => 60,
                'C4' => 80,
                'C5' => 60,
                'C6' => 80,
                'C7' => 60,
                'C8' => 100,
                'C9' => 60,
                'C10' => 80,
                'C11' => 60,
                'C12' => 80,
                'C13' => 60,
                'C14' => 80,
                'C15' => 80,
            ],
            'Putri Anggraeni Lestari' => [
                'alternatif' => 'A35',
                'C1' => 60,
                'C2' => 40,
                'C3' => 60,
                'C4' => 80,
                'C5' => 80,
                'C6' => 40,
                'C7' => 40,
                'C8' => 60,
                'C9' => 40,
                'C10' => 60,
                'C11' => 60,
                'C12' => 40,
                'C13' => 80,
                'C14' => 60,
                'C15' => 40,
            ],
            'Bambang Sudrajat' => [
                'alternatif' => 'A36',
                'C1' => 60,
                'C2' => 100,
                'C3' => 60,
                'C4' => 60,
                'C5' => 60,
                'C6' => 80,
                'C7' => 60,
                'C8' => 80,
                'C9' => 80,
                'C10' => 100,
                'C11' => 60,
                'C12' => 80,
                'C13' => 60,
                'C14' => 60,
                'C15' => 100,
            ],
            'Iwan Sutrisno' => [
                'alternatif' => 'A43',
                'C1' => 60,
                'C2' => 40,
                'C3' => 60,
                'C4' => 80,
                'C5' => 80,
                'C6' => 40,
                'C7' => 40,
                'C8' => 60,
                'C9' => 40,
                'C10' => 80,
                'C11' => 60,
                'C12' => 40,
                'C13' => 80,
                'C14' => 60,
                'C15' => 40,
            ],
            'Desi Aprilia Sari' => [
                'alternatif' => 'A45',
                'C1' => 60,
                'C2' => 60,
                'C3' => 80,
                'C4' => 60,
                'C5' => 60,
                'C6' => 80,
                'C7' => 100,
                'C8' => 80,
                'C9' => 60,
                'C10' => 60,
                'C11' => 60,
                'C12' => 40,
                'C13' => 60,
                'C14' => 80,
                'C15' => 60,
            ],
            'Luki Setiawan Ramdani' => [
                'alternatif' => 'A50',
                'C1' => 80,
                'C2' => 80,
                'C3' => 60,
                'C4' => 80,
                'C5' => 40,
                'C6' => 60,
                'C7' => 80,
                'C8' => 80,
                'C9' => 60,
                'C10' => 80,
                'C11' => 40,
                'C12' => 60,
                'C13' => 80,
                'C14' => 100,
                'C15' => 60,
            ],
            'Sri Utami Lestari' => [
                'alternatif' => 'A51',
                'C1' => 40,
                'C2' => 60,
                'C3' => 60,
                'C4' => 100,
                'C5' => 80,
                'C6' => 80,
                'C7' => 80,
                'C8' => 60,
                'C9' => 80,
                'C10' => 60,
                'C11' => 80,
                'C12' => 80,
                'C13' => 60,
                'C14' => 100,
                'C15' => 80,
            ],
            'Sandi Yudha' => [
                'alternatif' => 'A57',
                'C1' => 60,
                'C2' => 60,
                'C3' => 80,
                'C4' => 60,
                'C5' => 80,
                'C6' => 60,
                'C7' => 60,
                'C8' => 80,
                'C9' => 60,
                'C10' => 80,
                'C11' => 60,
                'C12' => 40,
                'C13' => 60,
                'C14' => 60,
                'C15' => 60,
            ],
            'Fajar Nugroho' => [
                'alternatif' => 'A58',
                'C1' => 80,
                'C2' => 80,
                'C3' => 100,
                'C4' => 60,
                'C5' => 80,
                'C6' => 60,
                'C7' => 60,
                'C8' => 60,
                'C9' => 60,
                'C10' => 60,
                'C11' => 80,
                'C12' => 60,
                'C13' => 80,
                'C14' => 80,
                'C15' => 80,
            ],
            'Amalia Fitriani Rahayu' => [
                'alternatif' => 'A59',
                'C1' => 60,
                'C2' => 60,
                'C3' => 60,
                'C4' => 40,
                'C5' => 60,
                'C6' => 60,
                'C7' => 80,
                'C8' => 100,
                'C9' => 60,
                'C10' => 80,
                'C11' => 60,
                'C12' => 80,
                'C13' => 60,
                'C14' => 60,
                'C15' => 60,
            ],
        ]; // Hasil Evaluasi Tahap 3


        foreach ($evaluationList as $fullname => $scores) {
            // Ambil data karyawan dari evaluation_employee_data
            $employee = DB::table('evaluation_employee_data')
                ->where('fullname', $fullname)
                ->where('evaluation_stage', strtoupper($targetStage))
                ->first();

            if (!$employee) {
                echo "Data untuk $fullname tidak ditemukan di evaluation_employee_data.\n";
                continue;
            }

            // Ambil user dari tabel users
            $user = User::where('email', $employee->email)->first();
            if (!$user) {
                echo "User dengan email {$employee->email} tidak ditemukan.\n";
                continue;
            }

            // Gabungkan data untuk validasi dan pemrosesan
            $data = array_merge($scores, [
                'fullname'           => $employee->fullname,
                'email'              => $employee->email,
                'departement'        => $employee->departement,
                'employeementStatus' => $employee->employeementStatus,
                'evaluation_years'   => $employee->evaluation_years,
                'evaluation_stage'   => $employee->evaluation_stage,
                'user_id'            => $user->id,
                'alternatif'         => 'A' . $employee->id,
            ]);

            // Kirim ke helper untuk diproses
            EvaluationProcessor::process($data, $user);
        }
    }
}
